# Generated by Django 4.1 on 2023-02-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seek', '0009_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_image',
            new_name='UserImage',
        ),
    ]
